### ISSUE TITLE
Time Out

### ISSUE THREAD

**Issue by AR98** [cruxrebels/InterviewBit#15]
Hey according to your code nextRight(B) calling same node  again which definitely gives wrong ans You should replace it with nextRight(B->next).

**Comment by cruxrebels** [comment]
Hi @AR98,

Since you haven't mentioned the file name or code where you're facing this issue, I took the liberty to search for `nextRight(B)` in this Repository and found out it being used in (PopulateNextRightPointersTree.cpp)[https://github.com/cruxrebels/InterviewBit/blob/7fd530657e43c68d3c8d07af093674bf761d9f21/Trees/PopulateNextRightPointersTree.cpp#L76]. I've verified this solution is passing fine on [Online Judge](https://www.interviewbit.com/problems/populate-next-right-pointers-tree/).

Resolving this issue, please re-open in case you face any more issue.
